//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PeakF1.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Driver
    {
        public Driver()
        {
            this.RaceResults = new HashSet<RaceResult>();
        }
    
        public int Id { get; set; }
        public int TeamId { get; set; }
    
        public virtual Team Team { get; set; }
        public virtual ICollection<RaceResult> RaceResults { get; set; }
    }
}
