//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PeakF1.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PredictionDetail
    {
        public int Id { get; set; }
        public int PredictionId { get; set; }
        public int DriverId { get; set; }
        public int Position { get; set; }
        public decimal Score { get; set; }
    
        public virtual Prediction Prediction { get; set; }
        public virtual Driver Driver { get; set; }
    }
}
